GET http://localhost:5229/api/Empleado HTTP/1.1
Content-Type: application/json
Authorization: bearer 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyIiwicm9sZSI6IkFkbWluaXN0cmFkb3IiLCJuYmYiOjE2Nzg1NTI4MTAsImV4cCI6MTY3ODYzOTIxMCwiaWF0IjoxNjc4NTUyODEwfQ.8pI-WiZzc1ICNqC2qCAnMF-CwUpFMznsle42ctNYiAQ'
